import { defineConfig } from "oxlint"

export default defineConfig({
  env: {
    builtin: true,
    node: true,
  },
  ignorePatterns: [
    "dist",
    "node_modules",
    "coverage",
    ".magi",
    ".worktrees",
    "*.generated.ts",
  ],
  jsPlugins: [
    "eslint-plugin-unused-imports",
    "eslint-plugin-perfectionist",
    {
      name: "import-alias",
      specifier: "@limegrass/eslint-plugin-import-alias",
    },
  ],
  options: { typeAware: true },
  plugins: ["eslint", "typescript", "unicorn", "import", "vitest"],
  rules: {
    "no-console": ["warn", { allow: ["warn", "error"] }],
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "no-empty": "off",
    "no-prototype-builtins": "off",
    "no-useless-escape": "off",
    "no-var": "error",

    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": "off",
    "typescript/consistent-indexed-object-style": ["error", "index-signature"],
    "typescript/consistent-type-exports": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/dot-notation": "warn",
    "typescript/no-empty-object-type": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-extraneous-class": "error",
    "typescript/no-floating-promises": "off",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "off",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-misused-spread": "off",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-boolean-literal-compare": "warn",
    "typescript/no-unnecessary-condition": "warn",
    "typescript/no-unnecessary-template-expression": "warn",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "warn",
    "typescript/no-unsafe-function-type": "off",
    "typescript/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "typescript/prefer-find": "warn",
    "typescript/prefer-function-type": "off",
    "typescript/prefer-includes": "warn",
    "typescript/prefer-literal-enum-member": "warn",
    "typescript/prefer-namespace-keyword": "warn",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-reduce-type-parameter": "warn",
    "typescript/prefer-string-starts-ends-with": "warn",
    "typescript/require-await": "error",

    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],

    "unused-imports/no-unused-imports": "error",

    "import-alias/import-alias": [
      "error",
      { relativeImportOverrides: [{ depth: 0, path: "." }] },
    ],

    "perfectionist/sort-array-includes": ["warn", { type: "natural" }],
    "perfectionist/sort-exports": [
      "error",
      { partitionByNewLine: true, type: "natural" },
    ],
    "perfectionist/sort-imports": [
      "error",
      {
        groups: [
          "type-import",
          ["type-parent", "type-sibling", "type-index"],
          "type-internal",
          ["value-builtin", "value-external"],
          "value-internal",
          ["value-parent", "value-sibling", "value-index"],
          "ts-equals-import",
          "unknown",
        ],
        newlinesBetween: "ignore",
        newlinesInside: "ignore",
        partitionByNewLine: true,
        type: "natural",
      },
    ],
    "perfectionist/sort-interfaces": [
      "warn",
      { partitionByNewLine: true, type: "natural" },
    ],
    "perfectionist/sort-intersection-types": ["warn", { type: "natural" }],
    "perfectionist/sort-jsx-props": ["warn", { type: "natural" }],
    "perfectionist/sort-maps": ["warn", { type: "natural" }],
    "perfectionist/sort-named-exports": ["warn", { type: "natural" }],
    "perfectionist/sort-named-imports": ["warn", { type: "natural" }],
    "perfectionist/sort-object-types": [
      "warn",
      { partitionByNewLine: true, type: "natural" },
    ],
    "perfectionist/sort-objects": [
      "warn",
      { partitionByNewLine: true, type: "natural" },
    ],
    "perfectionist/sort-sets": ["warn", { type: "natural" }],
    "perfectionist/sort-union-types": ["warn", { type: "natural" }],

    "vitest/consistent-each-for": "error",
    "vitest/consistent-test-filename": "error",
    "vitest/consistent-test-it": ["error", { fn: "test" }],
    "vitest/consistent-vitest-vi": "error",
    "vitest/expect-expect": "off",
    "vitest/hoisted-apis-on-top": "error",
    "vitest/no-alias-methods": "error",
    "vitest/no-commented-out-tests": "error",
    "vitest/no-conditional-in-test": "off",
    "vitest/no-conditional-tests": "error",
    "vitest/no-disabled-tests": "error",
    "vitest/no-duplicate-hooks": "error",
    "vitest/no-focused-tests": "error",
    "vitest/no-identical-title": "error",
    "vitest/no-import-node-test": "error",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/no-interpolation-in-snapshots": "error",
    "vitest/no-large-snapshots": "error",
    "vitest/no-mocks-import": "error",
    "vitest/no-restricted-matchers": "error",
    "vitest/no-standalone-expect": "error",
    "vitest/no-test-prefixes": "error",
    "vitest/no-test-return-statement": "error",
    "vitest/prefer-called-exactly-once-with": "error",
    "vitest/prefer-called-once": "off",
    "vitest/prefer-called-times": "off",
    "vitest/prefer-called-with": "error",
    "vitest/prefer-comparison-matcher": "error",
    "vitest/prefer-each": "error",
    "vitest/prefer-equality-matcher": "error",
    "vitest/prefer-expect-resolves": "error",
    "vitest/prefer-expect-type-of": "off",
    "vitest/prefer-hooks-in-order": "error",
    "vitest/prefer-hooks-on-top": "error",
    "vitest/prefer-import-in-mock": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-mock-promise-shorthand": "error",
    "vitest/prefer-spy-on": "error",
    "vitest/prefer-strict-boolean-matchers": "off",
    "vitest/prefer-strict-equal": "error",
    "vitest/prefer-to-be": "error",
    "vitest/prefer-to-be-falsy": "error",
    "vitest/prefer-to-be-object": "error",
    "vitest/prefer-to-be-truthy": "error",
    "vitest/prefer-to-contain": "error",
    "vitest/prefer-to-have-length": "error",
    "vitest/prefer-todo": "error",
    "vitest/require-awaited-expect-poll": "error",
    "vitest/require-hook": "error",
    "vitest/require-local-test-context-for-concurrent-snapshots": "error",
    "vitest/require-mock-type-parameters": "off",
    "vitest/require-test-timeout": "off",
    "vitest/require-to-throw-message": "error",
    "vitest/require-top-level-describe": "error",
    "vitest/valid-describe-callback": "error",
    "vitest/valid-expect": ["error", { alwaysAwait: true }],
    "vitest/valid-expect-in-promise": "error",
    "vitest/valid-title": "error",
    "vitest/warn-todo": "off",
  },
})
