name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup node and pnpm
        uses: ./.github/composite-actions/setup

      - name: Setup git user
        run: |
          git config --global user.email "hirotomo.yamada@avap.co.jp"
          git config --global user.name "hirotomoyamada"

      - name: Build
        run: pnpm build

      - name: Create release pull request or publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: pnpm release
          title: "Updated packages"
          commit: "ci(changesets): updated packages"
          setupGitUser: false
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create @dev release
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout ${{ github.ref_name }}
          pnpm release:dev
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
